### ISSUE TITLE
Implement check for resolving localhost

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1046] opened 2020-01-25 01:03 UTC
**Describe the error**

Customer reported the watcher container in the influxdb pod is constantly failing because it couldn't connect to influxdb as expected. After upgrading from 1.4.5 to 1.4.54, started to experience issues with InfluxDB. The pod kept restarting with status `CrashLoopBackOff`.

**Cause of the error**

The error was caused by a bad `localhost` resolution to an invalid ip which is not 127.0.0.1.

**Expected behavior**

A precheck should exist for `localhost` to resolve correctly in the cluster. This will ensure user fixes dns before continuing with installation.

**Comment by aelkugia** [comment] 2020-01-27 23:17
It was found that resolving from the dns server instead of `/etc/hosts/`is the Go behavior if cannot find `/etc/nsswitch` file in the container. 

There is a fix expected in Go 1.15 release. Discussion can be found here: https://github.com/golang/go/issues/35305

**Comment by terrywang** [comment] 2020-01-31 00:43
Just to correct, it's the `/etc/nsswitch.conf` file provided by `glibc` package on Fedora / EL and `libc-bin` on Debian/Ubuntu.

NOTE: On Arch Linux and its variants (e.g. Manjaro) that I use as workstation, the file is provided by `filesystem`.

**Comment by knisbet** [comment] 2020-02-28 19:16
It might be possible to just hardcode localhost in the coredns configuration. Depends a bit on whether the query is for localhost or localhost.<search>.

**Comment by knisbet** [comment] 2020-03-06 20:34
This is fixed in 5.5.x by https://github.com/gravitational/gravity/pull/1214 / https://github.com/gravitational/monitoring-app/pull/145 by fixing the cause of leaking localhost queries, as opposed to implementing a check for a capturing DNS resolver which is a valid customer deployment option.

**Closed** 2020-03-11 18:45 UTC
Labels: backport/5.5, backport/6.1, backport/6.3, enhancement, priority/1, support-load
