### ISSUE TITLE
[6.1.x] tele build fails to pull planet package

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#2125] opened 2020-09-14 10:41 UTC
### Description

**What happened**:
When building an enterprise application installer tarball, `tele build` fails to pull the corresponding planet package as the package dependency configuration is built using the stripped down version of the original application manifest with newer configuration parameters removed (e.g. `systemOptions.runtimePackage`).

**What you expected to happen**:
`tele build` succeeds

**How to reproduce it (as minimally and precisely as possible)**:
Build an application installer with `tele` 6.1.38.

### Environment

 - Gravity version [e.g. 7.0.11]: 6.1.38

**Comment by knisbet** [comment] 2020-09-14 17:40
This might be a duplicate of https://github.com/gravitational/gravity/issues/2040

**Closed** 2022-10-25 18:44 UTC
Labels: regression, port/7.0, port/master, type: kind/bug
