### ISSUE TITLE
devicemapper default

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#211] opened 2019-01-22 15:14 UTC
Encountered while providing support in the gravity community slack, it looks like a minimal app.yaml set devicemapper as the default docker graph driver. Since we're no longer supporting devicemapper, we should check to make sure we don't have any defaults still pointing to devicemapper. 

```
apiVersion: bundle.gravitational.io/v2
kind: Bundle
metadata:
 name: test
 resourceVersion: "1.0.0"
```

**Comment by klizhentas** [comment] 2019-01-22 15:27
Duplicate of https://github.com/gravitational/gravity.e/issues/3913

**Closed** 2019-02-06 19:24 UTC
