### ISSUE TITLE
[5.5.x] rollback infrastructure images from debian buster to stretch

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1223] opened 2020-03-09 22:16 UTC
Rollback images from debian `buster` to `stretch` upgrade (see [this issue](https://github.com/gravitational/gravity/issues/1222)) until it's clear what the culprit is.

As a possible long term solution consider updating (some of the) infrastructure images to be [distroless](https://github.com/GoogleContainerTools/distroless).

**Comment by wadells** [comment] 2020-03-13 16:10
Dupe of #1221.

**Closed** 2020-03-13 19:47 UTC
Labels: duplicate
