### ISSUE TITLE
gravity-site has "readiness probe failed" if it is not leader and produces thousands of events

### ISSUE THREAD

**Issue by aocheretnoy** [gravitational/gravity#1335] opened 2020-04-08 00:44 UTC
**Describe the bug**

`kubectl describe pods -n=kube-system gravity-site-xxxxxx`
in case if the pod is not leader, produces events

```
Events:
  Type     Reason     Age                      From                                 Message
  ----     ------     ----                     ----                                 -------
  Warning  Unhealthy  86s (x25710 over 2d23h)  kubelet, ip.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**To Reproduce**

Execute for not leader `kubectl describe pods -n=kube-system gravity-site-xxxxxx` 
**Expected behavior**

pods should be healthy 

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]:gravity-site:6.3.9
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by r0mant** [comment] 2020-04-08 00:49
Seems to be a dupe of https://github.com/gravitational/gravity/issues/1334.

**Closed by r0mant** 2020-04-08 00:49 UTC
