### ISSUE TITLE
[BUG] Monitoring application upgrade 5.5.36 -> 5.5.38 is failing with error

### ISSUE THREAD

**Issue by UnderGreen** [gravitational/gravity#1233] opened 2020-03-12 17:30 UTC
**Describe the bug**
```
---> Deleting old 'influxdb' resources
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
influxdb   0/0     0            0           15d
error: error executing template "{{(index .items 0).spec.nodeName}}": template: output:1:3: executing "output" at <index .items 0>: error calling index: index out of range: 0
```
Next try of the job marks the upgrade as completed even when upgrade didn't happen:
```
[root@ip-172-31-0-5 ec2-user]# kubectl logs monitoring-app-update-8bbba8-zc8qk -n kube-system
---> Assuming changeset from the environment: monitoring-5511
---> Checking: monitoring-5511
no errors detected for monitoring-5511
```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 5.5.38
 - Platform [e.g. Vmware, AWS]:

**Comment by r0mant** [comment] 2020-03-26 17:19
Duplicate of https://github.com/gravitational/gravity/issues/1281.

**Closed by r0mant** 2020-03-26 17:19 UTC
Labels: backport/5.5, bug, priority/1
