### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by NickBusey** [gravitational/gravity#85] opened 2018-10-31 20:57 UTC
There is another issue with build fails, but what I'm running into seems unrelated.

I have Docker 18.06.1

Running `$ git clone git@github.com:gravitational/gravity.git` then `$ make` results in:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build.assets build
cd /Users/nickgrownetics/Code/Grownetics/src && \
		LOCAL_GRAVITY_BUILDDIR=/Users/nickgrownetics/Code/gravity//build/5.3.2-3 \
			/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/nickgrownetics/Code/Grownetics/src/github.com/gravitational/gravity/build.assets -j \
			/Users/nickgrownetics/Code/gravity//build/5.3.2-3/gravity /Users/nickgrownetics/Code/gravity//build/5.3.2-3/tele
make: *** /Users/nickgrownetics/Code/Grownetics/src/github.com/gravitational/gravity/build.assets: No such file or directory.  Stop.
make[2]: *** [build-on-host] Error 2
make[1]: *** [build] Error 2
make: *** [build] Error 2
```

**Comment by kontsevoy** [comment] 2018-11-01 00:22
dupe of #62?

**Comment by NickBusey** [comment] 2018-11-01 01:41
> dupe of #62?

The very first line of my issue says there is another similar issue, and it is unrelated.

**Comment by kontsevoy** [comment] 2018-11-01 23:04
@NickBusey can't reproduce at the moment but will try later on a clean(er) Mac.

**Comment by kontsevoy** [comment] 2018-12-26 23:09
@NickBusey actually it looks exactly like #62 - docker fails to mount the build volume. I am going to mark this as a dupe, and we've yet to see this internally on any of the machines yet. But we'll keep the @62 open. Thanks for reporting this.

**Closed by kontsevoy** 2018-12-26 23:09 UTC

**Comment by di1214** [comment] 2019-02-10 20:19
i am hitting exactly the same issue on Mac. I think this is somehow related to GOPATH.
