### ISSUE TITLE
[Enhancement] Extend Gravity debug report

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1423] opened 2020-04-21 23:24 UTC
Extend Gravity debug report to include the following to start:

- Capture last command from host
- dmesg
- coredumpctl - grep output from it

**Comment by r0mant** [comment] 2020-06-16 22:27
Duplicate of https://github.com/gravitational/gravity/issues/1273.

**Closed by r0mant** 2020-06-16 22:27 UTC
