### ISSUE TITLE
Apiserver should set up --advertise-address to the address specified during install

### ISSUE THREAD

**Issue by klizhentas** [gravitational/gravity#175] opened 2019-01-10 01:57 UTC
## Description

Right now apiserver does not specify advertise address, what means that apiserver picks the default interface to advertise.

```

--advertise-address ip
--
  | The IP address on which to advertise the apiserver to members of the cluster. This address must be reachable by the rest of the cluster. If blank, the --bind-address will be used. If --bind-address is unspecified, the host's default interface will be used.

```

I suggest to set up the address to the advertise-ip provided by the user during install at all times.

**Comment by klizhentas** [comment] 2019-01-10 01:57
cc @knisbet

**Comment by dtshepherd** [comment] 2019-01-10 02:03
The documentation is misleading because it says "if blank, --bind-address will be used".  But that's not the case... You need to specify `--advertise-address` if you don't want kube-apiserver to setup `iptables` DNAT rules to the default interface (which kube-apiserver isn't even bound to!).

For reference, I hacked this line into `/lib/systemd/system/kube-apiserver.service`:
```
        --advertise-address=${PLANET_PUBLIC_IP} \
```
And restarted `kube-apiserver`.  This corrected the invalid `iptables` rule for kube-apiserver.

**Comment by a-palchikov** [comment] 2019-01-10 09:30
It is a duplicate of https://github.com/gravitational/gravity.e/issues/3802

**Closed** 2019-01-10 09:31 UTC
